### ISSUE TITLE
confirm the Ver of glfw

### ISSUE THREAD

**Issue by runjtu** [GREAT-WHU/RoadLib#1]
Thx your GREAT WORK! I use glfw3.4 and got these while running demo_mapping
[ PHASE ] : Semantic mapping.
[INFO] Incremental mapping: (frame) 1 (time) 280900.000
[INFO] Incremental mapping: (frame) 2 (time) 280900.100
... ...
[INFO] Incremental mapping: (frame) 48 (time) 280904.700
 [65545] EGL: Failed to find a suitable EGLConfig

Segmentation fault

**Comment by ZhouTangtang** [comment]
Thank you for your attention! I'm not very clear about the reason of this error. Here is the OpenGL information from my computer environment, as shown in the picture below. I hope this can serve as a reference for you.
![image](https://github.com/GREAT-WHU/RoadLib/assets/30310862/0953c67c-d0b5-44e9-a2ae-289b88b3ca8e)
 Perhaps you can check if mesa is installed. 
![image](https://github.com/GREAT-WHU/RoadLib/assets/30310862/f8444c03-5950-4837-b505-264787d0880b)
If you resolve the issue, please let me know.😊

**Comment by runjtu** [comment]
> Thank you for your attention! I'm not very clear about the reason of this error. Here is the OpenGL information from my computer environment, as shown in the picture below. I hope this can serve as a reference for you. ![image](https://private-user-images.githubusercontent.com/30310862/342557881-0953c67c-d0b5-44e9-a2ae-289b88b3ca8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyOTY4OTQsIm5iZiI6MTcxOTI5NjU5NCwicGF0aCI6Ii8zMDMxMDg2Mi8zNDI1NTc4ODEtMDk1M2M2N2MtZDBiNS00NGU5LWEyYWUtMjg5Yjg4YjNjYThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA2MjMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwY2Y2NjhmOTVhMTFkMGQwNmNlMmNmMjVmNGI3Njc5NzA3YWQwMDU2N2UyZTg5NWM5MDU3ZmUxNTBmODViOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CVqXuDju24o9yH0lLy_CcC12BmKksqAW8OiAhfUDBZk) Perhaps you can check if mesa is installed. ![image](https://private-user-images.githubusercontent.com/30310862/342557971-f8444c03-5950-4837-b505-264787d0880b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyOTY4OTQsIm5iZiI6MTcxOTI5NjU5NCwicGF0aCI6Ii8zMDMxMDg2Mi8zNDI1NTc5NzEtZjg0NDRjMDMtNTk1MC00ODM3LWI1MDUtMjY0Nzg3ZDA4ODBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA2MjMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwODc1NDQ3MzMxZjE1ZWE2OWFkMjhjNTM1NzYwNDBjMTllY2MxMjgwOGVjNWMxNzk1NWM3NjlmNzJmNjc1YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gxY0qKUY0wA_uT2rRIOHqw1iWJb8INkmLyaEb0SlXGQ) If you resolve the issue, please let me know.😊

fabulous! I make it, thx again for your attention!
