### ISSUE TITLE
目前的代码可以实现基于先验地图的重定位功能吗?

### ISSUE THREAD

**Issue by bobododosjl** [GREAT-WHU/RoadLib#10]

**Comment by yuxuanzhou97** [comment]
不太确定你的问题是指精细的地图匹配定位还是大范围内的重定位😂我这边都回答一下。
1）目前基于地图的定位只支持本代码建图模式生成的地图；如果是需要用别的格式的先验地图，理论上也是可行的，但是需要一定的适配。
2）如果是大范围内的重定位，目前的代码没有实现这块，暂时需要提供一个数米的初始位姿（这一块其实是比较值得研究的，即大范围内的基于矢量地图的初始定位

**Comment by yuxuanzhou97** [comment]
不太确定你的问题是指精细的地图匹配定位还是大范围内的重定位😂我这边都回答一下。
1）目前基于地图的定位只支持本代码建图模式生成的地图；如果是需要用别的格式的先验地图，理论上也是可行的，但是需要一定的适配，做一下地图格式的转换。
2）如果是大范围内的重定位，目前的代码没有实现这块，暂时需要提供一个数米的初始位姿（这一块其实是比较值得研究的，即大范围内的基于矢量地图的初始定位

**Comment by bobododosjl** [comment]
我说的应该是第二个，初始位置应该可以由高德地图提供的粗略位置信息表示。



---原始邮件---
发件人: "Zhou ***@***.***&gt;
发送时间: 2024年10月16日(周三) 晚上9:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [GREAT-WHU/RoadLib] 目前的代码可以实现基于先验地图的重定位功能吗? (Issue #10)




 
不太确定你的问题是指精细的地图匹配定位还是大范围内的重定位😂我这边都回答一下。
 1）目前基于地图的定位只支持本代码建图模式生成的地图；如果是需要用别的格式的先验地图，理论上也是可行的，但是需要一定的适配，做一下地图格式的转换。
 2）如果是大范围内的重定位，目前的代码没有实现这块，暂时需要提供一个数米的初始位姿（这一块其实是比较值得研究的，即大范围内的基于矢量地图的初始定位

**Comment by yuxuanzhou97** [comment]
嗯嗯👍👍
