### ISSUE TITLE
How to view bin files

### ISSUE THREAD

**Issue by tx-lidar** [GREAT-WHU/RoadLib#12]
Hello, I have generated a bin file after running the test data you provided. From my understanding, it should be a file similar to a point cloud map, but I can't open it with CloudCompare. It seems too large?.

**Comment by yuxuanzhou97** [comment]
You may use "scripts/view_map.py" for visualization of the binary map file. :)

**Comment by tx-lidar** [comment]
> You may use "scripts/view_map.py" for visualization of the binary map file. :)

Thank you very much！
