### ISSUE TITLE
How to create my own dataset for training

### ISSUE THREAD

**Issue by tiantian500** [GREAT-WHU/RoadLib#17]
Hello, thank you very much. I have reproduced the results of your work and applied the model you provided to perform inference tests on my own dataset. However, I found that there are cases of misclassification on my dataset. Therefore, I would like to retrain the model.
I am preparing to label road segmentation based on the types provided by ApolloScape, but I have some confusion about types that are not clearly defined. Could you provide your dataset for reference? Thank you very much!

**Comment by yuxuanzhou97** [comment]
Hello! You may send an e-mail to yuxuanzhou@whu.edu.cn, and I'll send you an example dataset for training.

**Comment by tiantian500** [comment]
Hello! Thank you very much for your willingness to help; it is very important to me.


                    Original Email         
         
       
From：                  "Zhou Yuxuan"         ***@***.***&gt;                 
Sending time：         2024-11-18- 16:16 
To：                  "GREAT-WHU/RoadLib"         ***@***.***&gt;                 
Cc recipient：                  "tiantian500"         ***@***.***&gt;         ,                "Author"         ***@***.***&gt;                 
Subject：         Re: [GREAT-WHU/RoadLib] How to create my own dataset for training(Issue #17) 




Hello! You may send an e-mail to ***@***.***, and I'll send you an example dataset for training.

**Comment by tiantian500** [comment]
Thank you to the author for sharing, it's very useful!
