### ISSUE TITLE
有关于数据坐标系的问题

### ISSUE THREAD

**Issue by LostDreammm** [GREAT-WHU/RoadLib#18]
请问一下采集到的gt数据是哪个坐标系下的数据呢？

**Comment by yuxuanzhou97** [comment]
"#timestamp, p^e_bx, p^e_by, p^e_bz, q^n_bw, q^n_bx, q^n_by, q^n_bz".

The position (1~3) is described in ECEF frame, while the values are shifted by tens of meters to avoid potential policy issue.
The quaternion (4~7) is described in the local East-North-Up frame (centered at the vehicle position), termed as n-frame. 

The local-to-global rotation transformation R^e_n can be obtained using "calcRne()" function.

**Comment by yuxuanzhou97** [comment]
"#timestamp, p^e_bx, p^e_by, p^e_bz, q^n_bw, q^n_bx, q^n_by, q^n_bz"

The position (1~3) is described in ECEF frame, while the values are shifted by tens of meters to avoid potential policy issue.
The quaternion (4~7) is described in the local East-North-Up frame (centered at the vehicle position), termed as n-frame. 

The local-to-global rotation transformation R^e_n can be obtained using "calcRne()" function.

**Comment by yuxuanzhou97** [comment]
#timestamp, p^e_bx, p^e_by, p^e_bz, q^n_bw, q^n_bx, q^n_by, q^n_bz

The position (1~3) is described in ECEF frame, while the coordinates are shifted by tens of meters to avoid potential policy issue.
The quaternion (4~7) is described in the local East-North-Up frame (centered at the vehicle position).

The local-to-global rotation transformation R^e_n can be obtained using "calcRne()".

**Comment by yuxuanzhou97** [comment]
#timestamp, p^e_bx, p^e_by, p^e_bz, q^n_bw, q^n_bx, q^n_by, q^n_bz

The position (1-3) is described in ECEF frame, while the coordinates are shifted by tens of meters to avoid potential policy issue.
The quaternion (4-7) is described in the local East-North-Up frame (centered at the vehicle position).

The local-to-global rotation transformation R^e_n can be obtained using "calcRne()".

**Comment by yuxuanzhou97** [comment]
@Yj107917  odo.txt中的位姿是局部的世界系下的（VIO的参考坐标系）。
对应于“#timestamp, p^w_bx, p^w_by, p^w_bz, q^w_bw, q^w_bx, q^w_by, q^w_bz”
而gt.txt的位姿是有地理含义的，位置是在ECEF系下，姿态是在东北天坐标系下
