### ISSUE TITLE
IPM calibration

### ISSUE THREAD

**Issue by lxy-mini** [GREAT-WHU/RoadLib#9]
Hello, how do you achieve calibration of your sensor? In other words, how do you get the accurate initial cg_alpha and cg_theta? I have seen some IPMs that implement IPM projection through the homography matrix of four vertices on the image.

**Comment by yuxuanzhou97** [comment]
Yes, homography-based calibration is a reliable implementation, while it needs some known landmarks on the ground.

There are also some targetless methods for the calibration, like "Online Camera-to-ground Calibration for Autonomous Driving" and "Ground-VIO". However, both of the two methods are not open-sourced, while they might provide some inspiration for you.

Actually, I'm planning to make a simple script to calibrate the camera-ground geometric parameters based on GT poses and ground feature tracking, as long as I get some free time.

**Comment by lxy-mini** [comment]
Okay, waiting for your good news
